---
- name: Create AWS infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vars/aws_ec2_vars.yml

  tasks:
    - name: Debug Environment Variables (Check AWS keys)
      ansible.builtin.debug:
        var: ansible_env
    - name: Create SG rules
      amazon.aws.ec2_security_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_description }}"
        region: "{{ region }}"
        purge_rules: false
        rules:
          - proto: tcp
            ports:
              - "{{ item.port }}"
            cidr_ip: "{{ item.cidr }}"
            rule_desc: "{{ item.description }}"
      loop: "{{ security_group_ports }}"